authentication:
  allowedGrantTypes:
    - password
  accessTokenExpireTimeMinutes: 60

database:
  host: localhost
  port: 3306
  database: medicinehelper
  username: root
  password:

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001