authentication:
  allowedGrantTypes:
    - password
  accessTokenExpireTimeMinutes: 60
  disabled: true

# Change default server ports
server:
  applicationConnectors:
  - type: http
    port: 9000
  adminConnectors:
  - type: http
    port: 9001